id: P004265
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 11:05:59.578594
source_metadata:
  id: bdr:W1KG3815
  title: ཀརྨ་པ་སྐུ་འཕྲེང་བཅུ་དྲུག་པ་ཚུན་རིམ་པར་བྱོན་པའི་རྣམ་ཐར་ཕྱོགས་བསྒྲིགས་
  author: ''
  volumes:
    3f04df486fcc4d61a00fa4df7d2d3580:
      image_group_id: I1KG3859
      title: ''
      volume_number: 1
      total_pages: 762
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
